# Import Library

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Uploading Csv file

In [4]:
df = pd.read_csv('C:/Users/vansh/Desktop/Vansh/Study material/Data science/Projects/mushrooms.csv')

In [5]:
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [6]:
# checking number of null values

df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [7]:
# Description of data

df.describe

<bound method NDFrame.describe of      class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-r

In [9]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [12]:
# Information of Data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [21]:
x = df.drop('class',axis=1)
y = df['class']

In [22]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=101,test_size=0.20)

In [25]:
print(x_test.shape)
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)

(1625, 22)
(6499, 22)
(1625,)
(6499,)


# Encoding data

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
oe = OrdinalEncoder()

In [47]:
oe

OrdinalEncoder()

In [54]:
x_train = oe.fit_transform(x_train)

In [55]:
x_train

array([[2., 0., 2., ..., 3., 4., 0.],
       [5., 2., 8., ..., 2., 3., 0.],
       [5., 2., 3., ..., 2., 4., 0.],
       ...,
       [2., 3., 4., ..., 2., 4., 5.],
       [2., 0., 3., ..., 2., 3., 1.],
       [2., 0., 3., ..., 1., 5., 4.]])

In [58]:
x_test = oe.fit_transform(x_test)

In [59]:
x_test

array([[5., 0., 9., ..., 1., 5., 0.],
       [5., 0., 4., ..., 3., 5., 0.],
       [5., 0., 9., ..., 1., 4., 4.],
       ...,
       [2., 0., 2., ..., 3., 5., 0.],
       [5., 0., 3., ..., 2., 3., 1.],
       [5., 3., 2., ..., 7., 4., 2.]])

In [76]:
from sklearn.preprocessing import LabelEncoder

In [80]:
le = LabelEncoder()

In [81]:
le

LabelEncoder()

In [82]:
y_test =le.fit_transform(y_test)

In [83]:
y_test

array([1, 0, 1, ..., 0, 0, 1])

In [84]:
y_train = le.fit_transform(y_train)

In [85]:
y_train

array([0, 1, 1, ..., 1, 0, 1])

In [49]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

# Logistic Regression

from sklearn.linear_model import LogisticRegression

In [88]:
model = LogisticRegression(random_state=42)

In [89]:
model

LogisticRegression(random_state=42)

In [90]:
model.fit(x_train,y_train)

LogisticRegression(random_state=42)

In [91]:
y_pred = model.predict(x_test)

In [92]:
y_pred

array([1, 0, 1, ..., 0, 0, 1])

In [93]:
from sklearn.metrics import accuracy_score

In [94]:
accuracy_score(y_test,y_pred)

0.9464615384615385

In [146]:
x = df.drop('class',axis=1)

In [148]:
y = df['class']

In [149]:
from sklearn.model_selection import train_test_split

In [150]:
x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=101,test_size=0.20)

In [152]:
x_train.columns

Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [153]:
x_train[['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat']] = oe.fit_transform(x_train[['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat']])

In [154]:
x_test[['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat']] = oe.transform(x_test[['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat']])

# Decision Tress 

In [159]:
from sklearn.tree import DecisionTreeClassifier

In [160]:
dtr = DecisionTreeClassifier(criterion='gini',max_depth = 5)

In [161]:
dtr

DecisionTreeClassifier(max_depth=5)

In [162]:
dtr.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [163]:
dtr_pred = dtr.predict(x_test)

In [164]:
dtr_pred

array(['p', 'e', 'p', ..., 'e', 'e', 'p'], dtype=object)

In [167]:
from sklearn.metrics import accuracy_score

In [168]:
accuracy_score(y_test,dtr_pred)

0.9766153846153847

# Random Forest 

In [107]:
from sklearn.ensemble import RandomForestClassifier

In [108]:
 rfc = RandomForestClassifier(max_features=100,random_state=42)

In [109]:
rfc

RandomForestClassifier(max_features=100, random_state=42)

In [110]:
rfc.fit(x_train,y_train)

RandomForestClassifier(max_features=100, random_state=42)

In [111]:
rfc_pred = rfc.predict(x_test)

In [112]:
rfc_pred

array([1, 0, 1, ..., 0, 0, 1])

In [113]:
from sklearn.metrics import accuracy_score,classification_report

In [114]:
accuracy_score(y_test,rfc_pred)

1.0